### ISSUE TITLE
Can't install the GitHub release apk.

### ISSUE THREAD

**Issue by HiperFall** [vmiklos/plees-tracker#298]
When I try to install GitHub release APK it says "App is not installed". Is it a bug? I would like to receive updates through GitHub release channel due to some of security issues of F-Droid. Thanks in advance.

**Comment by vmiklos** [comment]
The trouble is that .apk files have to be signed by somebody before you can install them on your phone. The release page has an automatically produced .apk, which is not suitable for the average user, since it's not signed. I'm not sure how to make them signed -- if I sign it with a throw-away key, then the next release can't be installed, because it'll be a different key.

F-Droid is exactly supposed to solve this problem for most users.

So I guess the short answer is that either you get it from F-Droid, build it from source (this is what I personally do) or you figure out how to lower your Android security settings (if possible at all) to allow installing an un-signed .apk.

Googling for "android install unsigned apk" probably gives you some hints. Does this help?

**Comment by HiperFall** [comment]
I don't know how but I am able to install other apps and update them from GitHub. I update them manually using RSS feed to get notified when the new update is available. The only app I use fdroid for is plees-tracker and it's a bit annoying.

If you have some simple instructions on building your app from source and signing it that can be done on macOS 10.15 I would definitely appreciate it. I don't know much about development.

**Comment by vmiklos** [comment]
Can you point out one or two projects where you get signed apks from their GH release pages? I would like to check if those are produced manually (which is what I would prefer to avoid) or automatically. Perhaps they know a trick I'm unfamiliar with. Thanks.

**Comment by vmiklos** [comment]
The downside is that android studio typically generates some key on your local machine for such build's signing, so if you switch machines, you won't have to upgrade to a new apk from an old apk.

Anyhow, here is a howto I found to do what you request:

https://proandroiddev.com/how-to-securely-build-and-sign-your-android-app-with-github-actions-ad5323452ce

This looks doable, I'll give it a try in the near future.

**Comment by HiperFall** [comment]
Yay, good news! I wish you good luck in this, can't wait to switch to the GitHub release APK!

**Comment by vmiklos** [comment]
Could you check if https://github.com/vmiklos/plees-tracker/releases/download/v7.4.0-rc1/app-release.apk does what you need? It's expected that you'll have to uninstall your old plees tracker manually (you can't upgrade when there is a signature change), so make sure you export your sleeps if you have any valuable data there.

**Comment by HiperFall** [comment]
It works! Yes, it does, what I need! So it will be automated through GitHub actions from now?

**Comment by vmiklos** [comment]
> So it will be automated through GitHub actions from now?

Yes :)
