### ISSUE TITLE
[Suggestion] Average time assumes one daily sleep period

### ISSUE THREAD

**Issue by pescepalla** [vmiklos/plees-tracker#308]
The "Average" stat isn't meaningful for anyone who takes naps. Assume I sleep 5 hours one night and then have a 1-hour nap to make up for the lost sleep, the average sleep time will be 3 hours, which is meaningless. Perhaps it would be more useful if the "Average" stat added up the entire sleeping time during the day.

**Comment by vmiklos** [comment]
The main screen contains two stats: the average length of all sleeps and the average of daily sums. This is explained here:

https://github.com/vmiklos/plees-tracker/blob/b30ba979710ce00f839c164b578ac16a18d5fa27/doc/README.adoc#main-activity

The second average doesn't assume just 1 sleep / day, so it sounds like that's what you're interested in and you can ignore the first. Is there anything to actually fix here?

**Comment by vmiklos** [comment]
You can certainly came up with various different interesting stats, the stats and the graphs activity + the dashboard is all about this. It seemed so far that one of "average of (sum of sleeps during a day)" and "average(individual sleeps)" is the most most useful one, that's why the dashboard features them.

I personally care about the first, but I understand that in case you sleep more than once a day, then that one is not useful; in this case hopefully the second is useful.

What is exactly the suggestion, would you like to only show one of these, and add an option to decide which one? Or add one more graph?

I don't mind more graphs if you're interested in contributing the code for that yourself.

Thanks for the brainstorming. :-)

**Comment by vmiklos** [comment]
Fine, after thinking about this a bit, I'll hide the "average" by default and only keep the "daily" column. And add settings + doc so people can show the first and/or the second as they wish. :-)

So now the default looks like this:

![image](https://user-images.githubusercontent.com/13838/212434596-2095fc0d-2acb-43e0-b26f-f503ed8dcb67.png)
