### ISSUE TITLE
option to hide timezone and seconds

### ISSUE THREAD

**Issue by foss-** [vmiklos/plees-tracker#309]
Currently Sleep time looks like this:

Started on `2022-08-20 23:30:21 +02:00`

Are seconds really needed or relevant for a sleep tracker? I think the better default would be to not show seconds for `Started on`, `Stopped on` and `Slept for`.

Also wondering why the time zone is shown. This may be relevant if you are traveling often. If you are at home this seems irrelevant.

**Comment by vmiklos** [comment]
> Are seconds really needed or relevant for a sleep tracker?

That is mostly just helpful when you test: otherwise you need to wait a minute between start and stop when you want to verify that the measuring actually works. Or you just hide the seconds for start/stop but still show it for the duration, which is a bit inconsistent.

> Also wondering why the time zone is shown.

This is helpful in countries that do daylight saving time changes. E.g. here sleeping from 2am to 3am usually means 1 hour duration, but sometimes it's 0 or 2. Without timezones, this just looks buggy.

But sure, adding a "compact time view" (or similarly named) option is fine. Are you interested in sending a PR for this yourself?

**Comment by foss-** [comment]
Sadly I am not a developer, so if you accept feature request without PR follow-up this could remain open in the tracker. If you don't do that, feel free to close the issue otherwise.
