### ISSUE TITLE
There should be option to add timings later part of the day by selecting DataTime dropdown

### ISSUE THREAD

**Issue by zaheernathani** [vmiklos/plees-tracker#52]
There should be option to add timings later part of the day by selecting DataTime dropdown.

Currently, we only have option to record time only by "start" button; but what if we forgot it and next morning I want to add timings manually. Similar option is available on Google Fit.

**Comment by voxitme** [comment]
> There should be option to add timings later part of the day by selecting DataTime dropdown.
> 
> Currently, we only have option to record time only by "start" button; but what if we forgot it and next morning I want to add timings manually. Similar option is available on Google Fit.

+1 And sometimes we can also need to edit the beginning timestamp because we know it took us 30min to fall asleep for example

**Comment by vmiklos** [comment]
If you want to modify an existing sleep, that already works, see #2 

This issue is about creating a sleep manually. Will have think about what's a good UI for that. One option would be to make the floating action button result in some kind of popup, where you can choose between start and create, but that may be too annoying, given that you typically start and only rarely create.

**Comment by voxitme** [comment]
> If you want to modify an existing sleep, that already works, see #2

Thanks and sorry for not noticing!

**Comment by vmiklos** [comment]
Perhaps a new menu item that would add a new sleep, defaulting to $now for start and end and you could edit it?

**Comment by maguilara** [comment]
Sorry for chiming in, but this would be great :) I track my sleep time using my smartband and I'd like to log it somewhere else, since my smartband app is disconnected from the internet for privacy reasons, an also given that it's not always user-friendly to export data from these proprietary apps if I wanted to do some graphs of my own. Editing works, but I wouldn't mind an option to do it directly. Maybe you could default the end time to $now and start time to ${now minus sleep goal time}? So you don't through the hassle of changing the date (assuming you go to sleep from one day to another). Thanks for your work, either way!

**Comment by vmiklos** [comment]
Fine, the question is how to expose this on the UI. My expectation is that 80% of users don't need this, so extending the floating action button at the bottom right corner to always choose if you want to just start tracking or manually adding a new sleep is not ideal: an extra question when the majority of the users choose one option all the time. As I asked back in Nov above: would a new menu item allowing this would be OK for you?

**Comment by maguilara** [comment]
I think that would work. I would also suggest some other approachs like adding a setting to change the default behaviour of the floating button to "add new sleep", or extending the floating button behaviour so that if you keep it pressed for certain amount of time, the new option appears displayed for the ocassions you need to log a sleep and you forgot to start your app. The first approach would suit users like me that belong that 20% and the second approach would enhance the experience of the 80% of users. I do reckon that keeping pressed the button route would probably require some sort of orientation/tutorial for the end user to discover this feature which would stay unknown otherwise. So, I'd probably suggest a mix between your suggestion (add a menu item) which would allow users that forgot to start their app (for the rare occassions that this might happen) + adding an option to change the default behaviour of the floating button for users like me that will use it 100% of the time like this.

**Comment by heyitsdeity** [comment]
A potential fix for this would be to switch the floating action button from "start" to a "+" icon which expands into the options "start timer" and "manual add." A similar UI behavior is used in the MEGA app:
<img src="https://user-images.githubusercontent.com/43617576/125169880-d79ee180-e171-11eb-8cfe-f82bc0486562.png" width="40%">

**Comment by zaheernathani** [comment]
No longer relevant
